const std = @import("std");
const sdl = @import("sdl.zig").sdl;

const SDLKey = struct {
    name: [:0]const u8,
    value: u32,
};

const sdl_keys = [_]SDLKey{
    // keyboard
    .{ .name = "UNKNOWN", .value = sdl.SDLK_UNKNOWN },
    .{ .name = "RETURN", .value = sdl.SDLK_RETURN },
    .{ .name = "ESCAPE", .value = sdl.SDLK_ESCAPE },
    .{ .name = "BACKSPACE", .value = sdl.SDLK_BACKSPACE },
    .{ .name = "TAB", .value = sdl.SDLK_TAB },
    .{ .name = "SPACE", .value = sdl.SDLK_SPACE },
    .{ .name = "EXCLAIM", .value = sdl.SDLK_EXCLAIM },
    .{ .name = "DBLAPOSTROPHE", .value = sdl.SDLK_DBLAPOSTROPHE },
    .{ .name = "HASH", .value = sdl.SDLK_HASH },
    .{ .name = "DOLLAR", .value = sdl.SDLK_DOLLAR },
    .{ .name = "PERCENT", .value = sdl.SDLK_PERCENT },
    .{ .name = "AMPERSAND", .value = sdl.SDLK_AMPERSAND },
    .{ .name = "APOSTROPHE", .value = sdl.SDLK_APOSTROPHE },
    .{ .name = "LEFTPAREN", .value = sdl.SDLK_LEFTPAREN },
    .{ .name = "RIGHTPAREN", .value = sdl.SDLK_RIGHTPAREN },
    .{ .name = "ASTERISK", .value = sdl.SDLK_ASTERISK },
    .{ .name = "PLUS", .value = sdl.SDLK_PLUS },
    .{ .name = "COMMA", .value = sdl.SDLK_COMMA },
    .{ .name = "MINUS", .value = sdl.SDLK_MINUS },
    .{ .name = "PERIOD", .value = sdl.SDLK_PERIOD },
    .{ .name = "SLASH", .value = sdl.SDLK_SLASH },
    .{ .name = "N0", .value = sdl.SDLK_0 },
    .{ .name = "N1", .value = sdl.SDLK_1 },
    .{ .name = "N2", .value = sdl.SDLK_2 },
    .{ .name = "N3", .value = sdl.SDLK_3 },
    .{ .name = "N4", .value = sdl.SDLK_4 },
    .{ .name = "N5", .value = sdl.SDLK_5 },
    .{ .name = "N6", .value = sdl.SDLK_6 },
    .{ .name = "N7", .value = sdl.SDLK_7 },
    .{ .name = "N8", .value = sdl.SDLK_8 },
    .{ .name = "N9", .value = sdl.SDLK_9 },
    .{ .name = "COLON", .value = sdl.SDLK_COLON },
    .{ .name = "SEMICOLON", .value = sdl.SDLK_SEMICOLON },
    .{ .name = "LESS", .value = sdl.SDLK_LESS },
    .{ .name = "EQUALS", .value = sdl.SDLK_EQUALS },
    .{ .name = "GREATER", .value = sdl.SDLK_GREATER },
    .{ .name = "QUESTION", .value = sdl.SDLK_QUESTION },
    .{ .name = "AT", .value = sdl.SDLK_AT },
    .{ .name = "LEFTBRACKET", .value = sdl.SDLK_LEFTBRACKET },
    .{ .name = "BACKSLASH", .value = sdl.SDLK_BACKSLASH },
    .{ .name = "RIGHTBRACKET", .value = sdl.SDLK_RIGHTBRACKET },
    .{ .name = "CARET", .value = sdl.SDLK_CARET },
    .{ .name = "UNDERSCORE", .value = sdl.SDLK_UNDERSCORE },
    .{ .name = "GRAVE", .value = sdl.SDLK_GRAVE },
    .{ .name = "A", .value = sdl.SDLK_A },
    .{ .name = "B", .value = sdl.SDLK_B },
    .{ .name = "C", .value = sdl.SDLK_C },
    .{ .name = "D", .value = sdl.SDLK_D },
    .{ .name = "E", .value = sdl.SDLK_E },
    .{ .name = "F", .value = sdl.SDLK_F },
    .{ .name = "G", .value = sdl.SDLK_G },
    .{ .name = "H", .value = sdl.SDLK_H },
    .{ .name = "I", .value = sdl.SDLK_I },
    .{ .name = "J", .value = sdl.SDLK_J },
    .{ .name = "K", .value = sdl.SDLK_K },
    .{ .name = "L", .value = sdl.SDLK_L },
    .{ .name = "M", .value = sdl.SDLK_M },
    .{ .name = "N", .value = sdl.SDLK_N },
    .{ .name = "O", .value = sdl.SDLK_O },
    .{ .name = "P", .value = sdl.SDLK_P },
    .{ .name = "Q", .value = sdl.SDLK_Q },
    .{ .name = "R", .value = sdl.SDLK_R },
    .{ .name = "S", .value = sdl.SDLK_S },
    .{ .name = "T", .value = sdl.SDLK_T },
    .{ .name = "U", .value = sdl.SDLK_U },
    .{ .name = "V", .value = sdl.SDLK_V },
    .{ .name = "W", .value = sdl.SDLK_W },
    .{ .name = "X", .value = sdl.SDLK_X },
    .{ .name = "Y", .value = sdl.SDLK_Y },
    .{ .name = "Z", .value = sdl.SDLK_Z },
    .{ .name = "LEFTBRACE", .value = sdl.SDLK_LEFTBRACE },
    .{ .name = "PIPE", .value = sdl.SDLK_PIPE },
    .{ .name = "RIGHTBRACE", .value = sdl.SDLK_RIGHTBRACE },
    .{ .name = "TILDE", .value = sdl.SDLK_TILDE },
    .{ .name = "DELETE", .value = sdl.SDLK_DELETE },
    .{ .name = "PLUSMINUS", .value = sdl.SDLK_PLUSMINUS },
    .{ .name = "CAPSLOCK", .value = sdl.SDLK_CAPSLOCK },
    .{ .name = "F1", .value = sdl.SDLK_F1 },
    .{ .name = "F2", .value = sdl.SDLK_F2 },
    .{ .name = "F3", .value = sdl.SDLK_F3 },
    .{ .name = "F4", .value = sdl.SDLK_F4 },
    .{ .name = "F5", .value = sdl.SDLK_F5 },
    .{ .name = "F6", .value = sdl.SDLK_F6 },
    .{ .name = "F7", .value = sdl.SDLK_F7 },
    .{ .name = "F8", .value = sdl.SDLK_F8 },
    .{ .name = "F9", .value = sdl.SDLK_F9 },
    .{ .name = "F10", .value = sdl.SDLK_F10 },
    .{ .name = "F11", .value = sdl.SDLK_F11 },
    .{ .name = "F12", .value = sdl.SDLK_F12 },
    .{ .name = "PRINTSCREEN", .value = sdl.SDLK_PRINTSCREEN },
    .{ .name = "SCROLLLOCK", .value = sdl.SDLK_SCROLLLOCK },
    .{ .name = "PAUSE", .value = sdl.SDLK_PAUSE },
    .{ .name = "INSERT", .value = sdl.SDLK_INSERT },
    .{ .name = "HOME", .value = sdl.SDLK_HOME },
    .{ .name = "PAGEUP", .value = sdl.SDLK_PAGEUP },
    .{ .name = "END", .value = sdl.SDLK_END },
    .{ .name = "PAGEDOWN", .value = sdl.SDLK_PAGEDOWN },
    .{ .name = "RIGHT", .value = sdl.SDLK_RIGHT },
    .{ .name = "LEFT", .value = sdl.SDLK_LEFT },
    .{ .name = "DOWN", .value = sdl.SDLK_DOWN },
    .{ .name = "UP", .value = sdl.SDLK_UP },
    .{ .name = "NUMLOCKCLEAR", .value = sdl.SDLK_NUMLOCKCLEAR },
    .{ .name = "KP_DIVIDE", .value = sdl.SDLK_KP_DIVIDE },
    .{ .name = "KP_MULTIPLY", .value = sdl.SDLK_KP_MULTIPLY },
    .{ .name = "KP_MINUS", .value = sdl.SDLK_KP_MINUS },
    .{ .name = "KP_PLUS", .value = sdl.SDLK_KP_PLUS },
    .{ .name = "KP_ENTER", .value = sdl.SDLK_KP_ENTER },
    .{ .name = "KP_1", .value = sdl.SDLK_KP_1 },
    .{ .name = "KP_2", .value = sdl.SDLK_KP_2 },
    .{ .name = "KP_3", .value = sdl.SDLK_KP_3 },
    .{ .name = "KP_4", .value = sdl.SDLK_KP_4 },
    .{ .name = "KP_5", .value = sdl.SDLK_KP_5 },
    .{ .name = "KP_6", .value = sdl.SDLK_KP_6 },
    .{ .name = "KP_7", .value = sdl.SDLK_KP_7 },
    .{ .name = "KP_8", .value = sdl.SDLK_KP_8 },
    .{ .name = "KP_9", .value = sdl.SDLK_KP_9 },
    .{ .name = "KP_0", .value = sdl.SDLK_KP_0 },
    .{ .name = "KP_PERIOD", .value = sdl.SDLK_KP_PERIOD },
    .{ .name = "APPLICATION", .value = sdl.SDLK_APPLICATION },
    .{ .name = "POWER", .value = sdl.SDLK_POWER },
    .{ .name = "KP_EQUALS", .value = sdl.SDLK_KP_EQUALS },
    .{ .name = "F13", .value = sdl.SDLK_F13 },
    .{ .name = "F14", .value = sdl.SDLK_F14 },
    .{ .name = "F15", .value = sdl.SDLK_F15 },
    .{ .name = "F16", .value = sdl.SDLK_F16 },
    .{ .name = "F17", .value = sdl.SDLK_F17 },
    .{ .name = "F18", .value = sdl.SDLK_F18 },
    .{ .name = "F19", .value = sdl.SDLK_F19 },
    .{ .name = "F20", .value = sdl.SDLK_F20 },
    .{ .name = "F21", .value = sdl.SDLK_F21 },
    .{ .name = "F22", .value = sdl.SDLK_F22 },
    .{ .name = "F23", .value = sdl.SDLK_F23 },
    .{ .name = "F24", .value = sdl.SDLK_F24 },
    .{ .name = "EXECUTE", .value = sdl.SDLK_EXECUTE },
    .{ .name = "HELP", .value = sdl.SDLK_HELP },
    .{ .name = "MENU", .value = sdl.SDLK_MENU },
    .{ .name = "SELECT", .value = sdl.SDLK_SELECT },
    .{ .name = "STOP", .value = sdl.SDLK_STOP },
    .{ .name = "AGAIN", .value = sdl.SDLK_AGAIN },
    .{ .name = "UNDO", .value = sdl.SDLK_UNDO },
    .{ .name = "CUT", .value = sdl.SDLK_CUT },
    .{ .name = "COPY", .value = sdl.SDLK_COPY },
    .{ .name = "PASTE", .value = sdl.SDLK_PASTE },
    .{ .name = "FIND", .value = sdl.SDLK_FIND },
    .{ .name = "MUTE", .value = sdl.SDLK_MUTE },
    .{ .name = "VOLUMEUP", .value = sdl.SDLK_VOLUMEUP },
    .{ .name = "VOLUMEDOWN", .value = sdl.SDLK_VOLUMEDOWN },
    .{ .name = "KP_COMMA", .value = sdl.SDLK_KP_COMMA },
    .{ .name = "KP_EQUALSAS400", .value = sdl.SDLK_KP_EQUALSAS400 },
    .{ .name = "ALTERASE", .value = sdl.SDLK_ALTERASE },
    .{ .name = "SYSREQ", .value = sdl.SDLK_SYSREQ },
    .{ .name = "CANCEL", .value = sdl.SDLK_CANCEL },
    .{ .name = "CLEAR", .value = sdl.SDLK_CLEAR },
    .{ .name = "PRIOR", .value = sdl.SDLK_PRIOR },
    .{ .name = "RETURN2", .value = sdl.SDLK_RETURN2 },
    .{ .name = "SEPARATOR", .value = sdl.SDLK_SEPARATOR },
    .{ .name = "OUT", .value = sdl.SDLK_OUT },
    .{ .name = "OPER", .value = sdl.SDLK_OPER },
    .{ .name = "CLEARAGAIN", .value = sdl.SDLK_CLEARAGAIN },
    .{ .name = "CRSEL", .value = sdl.SDLK_CRSEL },
    .{ .name = "EXSEL", .value = sdl.SDLK_EXSEL },
    .{ .name = "KP_00", .value = sdl.SDLK_KP_00 },
    .{ .name = "KP_000", .value = sdl.SDLK_KP_000 },
    .{ .name = "THOUSANDSSEPARATOR", .value = sdl.SDLK_THOUSANDSSEPARATOR },
    .{ .name = "DECIMALSEPARATOR", .value = sdl.SDLK_DECIMALSEPARATOR },
    .{ .name = "CURRENCYUNIT", .value = sdl.SDLK_CURRENCYUNIT },
    .{ .name = "CURRENCYSUBUNIT", .value = sdl.SDLK_CURRENCYSUBUNIT },
    .{ .name = "KP_LEFTPAREN", .value = sdl.SDLK_KP_LEFTPAREN },
    .{ .name = "KP_RIGHTPAREN", .value = sdl.SDLK_KP_RIGHTPAREN },
    .{ .name = "KP_LEFTBRACE", .value = sdl.SDLK_KP_LEFTBRACE },
    .{ .name = "KP_RIGHTBRACE", .value = sdl.SDLK_KP_RIGHTBRACE },
    .{ .name = "KP_TAB", .value = sdl.SDLK_KP_TAB },
    .{ .name = "KP_BACKSPACE", .value = sdl.SDLK_KP_BACKSPACE },
    .{ .name = "KP_A", .value = sdl.SDLK_KP_A },
    .{ .name = "KP_B", .value = sdl.SDLK_KP_B },
    .{ .name = "KP_C", .value = sdl.SDLK_KP_C },
    .{ .name = "KP_D", .value = sdl.SDLK_KP_D },
    .{ .name = "KP_E", .value = sdl.SDLK_KP_E },
    .{ .name = "KP_F", .value = sdl.SDLK_KP_F },
    .{ .name = "KP_XOR", .value = sdl.SDLK_KP_XOR },
    .{ .name = "KP_POWER", .value = sdl.SDLK_KP_POWER },
    .{ .name = "KP_PERCENT", .value = sdl.SDLK_KP_PERCENT },
    .{ .name = "KP_LESS", .value = sdl.SDLK_KP_LESS },
    .{ .name = "KP_GREATER", .value = sdl.SDLK_KP_GREATER },
    .{ .name = "KP_AMPERSAND", .value = sdl.SDLK_KP_AMPERSAND },
    .{ .name = "KP_DBLAMPERSAND", .value = sdl.SDLK_KP_DBLAMPERSAND },
    .{ .name = "KP_VERTICALBAR", .value = sdl.SDLK_KP_VERTICALBAR },
    .{ .name = "KP_DBLVERTICALBAR", .value = sdl.SDLK_KP_DBLVERTICALBAR },
    .{ .name = "KP_COLON", .value = sdl.SDLK_KP_COLON },
    .{ .name = "KP_HASH", .value = sdl.SDLK_KP_HASH },
    .{ .name = "KP_SPACE", .value = sdl.SDLK_KP_SPACE },
    .{ .name = "KP_AT", .value = sdl.SDLK_KP_AT },
    .{ .name = "KP_EXCLAM", .value = sdl.SDLK_KP_EXCLAM },
    .{ .name = "KP_MEMSTORE", .value = sdl.SDLK_KP_MEMSTORE },
    .{ .name = "KP_MEMRECALL", .value = sdl.SDLK_KP_MEMRECALL },
    .{ .name = "KP_MEMCLEAR", .value = sdl.SDLK_KP_MEMCLEAR },
    .{ .name = "KP_MEMADD", .value = sdl.SDLK_KP_MEMADD },
    .{ .name = "KP_MEMSUBTRACT", .value = sdl.SDLK_KP_MEMSUBTRACT },
    .{ .name = "KP_MEMMULTIPLY", .value = sdl.SDLK_KP_MEMMULTIPLY },
    .{ .name = "KP_MEMDIVIDE", .value = sdl.SDLK_KP_MEMDIVIDE },
    .{ .name = "KP_PLUSMINUS", .value = sdl.SDLK_KP_PLUSMINUS },
    .{ .name = "KP_CLEAR", .value = sdl.SDLK_KP_CLEAR },
    .{ .name = "KP_CLEARENTRY", .value = sdl.SDLK_KP_CLEARENTRY },
    .{ .name = "KP_BINARY", .value = sdl.SDLK_KP_BINARY },
    .{ .name = "KP_OCTAL", .value = sdl.SDLK_KP_OCTAL },
    .{ .name = "KP_DECIMAL", .value = sdl.SDLK_KP_DECIMAL },
    .{ .name = "KP_HEXADECIMAL", .value = sdl.SDLK_KP_HEXADECIMAL },
    .{ .name = "LCTRL", .value = sdl.SDLK_LCTRL },
    .{ .name = "LSHIFT", .value = sdl.SDLK_LSHIFT },
    .{ .name = "LALT", .value = sdl.SDLK_LALT },
    .{ .name = "LGUI", .value = sdl.SDLK_LGUI },
    .{ .name = "RCTRL", .value = sdl.SDLK_RCTRL },
    .{ .name = "RSHIFT", .value = sdl.SDLK_RSHIFT },
    .{ .name = "RALT", .value = sdl.SDLK_RALT },
    .{ .name = "RGUI", .value = sdl.SDLK_RGUI },
    .{ .name = "MODE", .value = sdl.SDLK_MODE },
    .{ .name = "SLEEP", .value = sdl.SDLK_SLEEP },
    .{ .name = "WAKE", .value = sdl.SDLK_WAKE },
    .{ .name = "CHANNEL_INCREMENT", .value = sdl.SDLK_CHANNEL_INCREMENT },
    .{ .name = "CHANNEL_DECREMENT", .value = sdl.SDLK_CHANNEL_DECREMENT },
    .{ .name = "MEDIA_PLAY", .value = sdl.SDLK_MEDIA_PLAY },
    .{ .name = "MEDIA_PAUSE", .value = sdl.SDLK_MEDIA_PAUSE },
    .{ .name = "MEDIA_RECORD", .value = sdl.SDLK_MEDIA_RECORD },
    .{ .name = "MEDIA_FAST_FORWARD", .value = sdl.SDLK_MEDIA_FAST_FORWARD },
    .{ .name = "MEDIA_REWIND", .value = sdl.SDLK_MEDIA_REWIND },
    .{ .name = "MEDIA_NEXT_TRACK", .value = sdl.SDLK_MEDIA_NEXT_TRACK },
    .{ .name = "MEDIA_PREVIOUS_TRACK", .value = sdl.SDLK_MEDIA_PREVIOUS_TRACK },
    .{ .name = "MEDIA_STOP", .value = sdl.SDLK_MEDIA_STOP },
    .{ .name = "MEDIA_EJECT", .value = sdl.SDLK_MEDIA_EJECT },
    .{ .name = "MEDIA_PLAY_PAUSE", .value = sdl.SDLK_MEDIA_PLAY_PAUSE },
    .{ .name = "MEDIA_SELECT", .value = sdl.SDLK_MEDIA_SELECT },
    .{ .name = "AC_NEW", .value = sdl.SDLK_AC_NEW },
    .{ .name = "AC_OPEN", .value = sdl.SDLK_AC_OPEN },
    .{ .name = "AC_CLOSE", .value = sdl.SDLK_AC_CLOSE },
    .{ .name = "AC_EXIT", .value = sdl.SDLK_AC_EXIT },
    .{ .name = "AC_SAVE", .value = sdl.SDLK_AC_SAVE },
    .{ .name = "AC_PRINT", .value = sdl.SDLK_AC_PRINT },
    .{ .name = "AC_PROPERTIES", .value = sdl.SDLK_AC_PROPERTIES },
    .{ .name = "AC_SEARCH", .value = sdl.SDLK_AC_SEARCH },
    .{ .name = "AC_HOME", .value = sdl.SDLK_AC_HOME },
    .{ .name = "AC_BACK", .value = sdl.SDLK_AC_BACK },
    .{ .name = "AC_FORWARD", .value = sdl.SDLK_AC_FORWARD },
    .{ .name = "AC_STOP", .value = sdl.SDLK_AC_STOP },
    .{ .name = "AC_REFRESH", .value = sdl.SDLK_AC_REFRESH },
    .{ .name = "AC_BOOKMARKS", .value = sdl.SDLK_AC_BOOKMARKS },
    .{ .name = "SOFTLEFT", .value = sdl.SDLK_SOFTLEFT },
    .{ .name = "SOFTRIGHT", .value = sdl.SDLK_SOFTRIGHT },
    .{ .name = "CALL", .value = sdl.SDLK_CALL },
    .{ .name = "ENDCALL", .value = sdl.SDLK_ENDCALL },
    .{ .name = "LEFT_TAB", .value = sdl.SDLK_LEFT_TAB },
    .{ .name = "LEVEL5_SHIFT", .value = sdl.SDLK_LEVEL5_SHIFT },
    .{ .name = "MULTI_KEY_COMPOSE", .value = sdl.SDLK_MULTI_KEY_COMPOSE },
    .{ .name = "LMETA", .value = sdl.SDLK_LMETA },
    .{ .name = "RMETA", .value = sdl.SDLK_RMETA },
    .{ .name = "LHYPER", .value = sdl.SDLK_LHYPER },
    .{ .name = "RHYPER", .value = sdl.SDLK_RHYPER },
    // SDL_KMOD_
    // .{ .name = "KMOD_NONE", .value = sdl.SDL_KMOD_NONE },
    // .{ .name = "KMOD_LSHIFT", .value = sdl.SDL_KMOD_LSHIFT },
    // .{ .name = "KMOD_RSHIFT", .value = sdl.SDL_KMOD_RSHIFT },
    // .{ .name = "KMOD_LEVEL5", .value = sdl.SDL_KMOD_LEVEL5 },
    // .{ .name = "KMOD_LCTRL", .value = sdl.SDL_KMOD_LCTRL },
    // .{ .name = "KMOD_RCTRL", .value = sdl.SDL_KMOD_RCTRL },
    // .{ .name = "KMOD_LALT", .value = sdl.SDL_KMOD_LALT },
    // .{ .name = "KMOD_RALT", .value = sdl.SDL_KMOD_RALT },
    // .{ .name = "KMOD_LGUI", .value = sdl.SDL_KMOD_LGUI },
    // .{ .name = "KMOD_RGUI", .value = sdl.SDL_KMOD_RGUI },
    // .{ .name = "KMOD_NUM", .value = sdl.SDL_KMOD_NUM },
    // .{ .name = "KMOD_CAPS", .value = sdl.SDL_KMOD_CAPS },
    // .{ .name = "KMOD_MODE", .value = sdl.SDL_KMOD_MODE },
    // .{ .name = "KMOD_SCROLL", .value = sdl.SDL_KMOD_SCROLL },
    // .{ .name = "KMOD_CTRL", .value = sdl.SDL_KMOD_CTRL },
    // .{ .name = "KMOD_SHIFT", .value = sdl.SDL_KMOD_SHIFT },
    // .{ .name = "KMOD_ALT", .value = sdl.SDL_KMOD_ALT },
    // .{ .name = "KMOD_GUI", .value = sdl.SDL_KMOD_GUI },
    // mouse
    .{ .name = "BUTTON_LEFT", .value = sdl.SDL_BUTTON_LEFT },
    .{ .name = "BUTTON_MIDDLE", .value = sdl.SDL_BUTTON_MIDDLE },
    .{ .name = "BUTTON_RIGHT", .value = sdl.SDL_BUTTON_RIGHT },
    .{ .name = "BUTTON_X1", .value = sdl.SDL_BUTTON_X1 },
    .{ .name = "BUTTON_X2", .value = sdl.SDL_BUTTON_X2 },
};

pub const EventType = enum {
    Unknown,
    Quit,
    KeyPressed,
    KeyReleased,
    MouseButtonPressed,
    MouseButtonReleased,
    MouseMoved,

    fn fromSDL(sdlEventType: u32) EventType {
        return switch (sdlEventType) {
            sdl.SDL_EVENT_QUIT => EventType.Quit,
            sdl.SDL_EVENT_KEY_DOWN => EventType.KeyPressed,
            sdl.SDL_EVENT_KEY_UP => EventType.KeyReleased,
            sdl.SDL_EVENT_MOUSE_BUTTON_DOWN => EventType.MouseButtonPressed,
            sdl.SDL_EVENT_MOUSE_BUTTON_UP => EventType.MouseButtonReleased,
            sdl.SDL_EVENT_MOUSE_MOTION => EventType.MouseMoved,
            else => EventType.Unknown,
        };
    }

    fn isKeyboardEvent(self: EventType) bool {
        return self == EventType.KeyPressed or self == EventType.KeyReleased;
    }

    fn isMouseEvent(self: EventType) bool {
        return self == EventType.MouseMoved or self == EventType.MouseButtonPressed or self == EventType.MouseButtonReleased;
    }
};

fn buildKey() type {
    var fields: [sdl_keys.len]std.builtin.Type.EnumField = undefined;
    for (0..sdl_keys.len) |i| {
        fields[i] = .{ .name = sdl_keys[i].name, .value = sdl_keys[i].value };
    }

    return @Type(.{ .@"enum" = .{
        .decls = &.{},
        .tag_type = i32,
        .fields = &fields,
        .is_exhaustive = true,
    } });
}

pub const Key = buildKey();

pub const Event = struct {
    eventType: EventType,
    key: Key,
    mouse_x: f32,
    mouse_y: f32,
    mouse_x_rel: f32,
    mouse_y_rel: f32,

    pub fn fromSDL(sdlEvent: sdl.SDL_Event) Event {
        const eventType: EventType = EventType.fromSDL(sdlEvent.type);

        var key: Key = Key.UNKNOWN;
        if (eventType.isKeyboardEvent())
            key = @enumFromInt(sdlEvent.key.key);

        var mouse_x: f32 = 0;
        var mouse_y: f32 = 0;
        var mouse_x_rel: f32 = 0;
        var mouse_y_rel: f32 = 0;
        if (eventType.isMouseEvent()) {
            mouse_x = sdlEvent.motion.x;
            mouse_y = sdlEvent.motion.y;
            mouse_x_rel = sdlEvent.motion.xrel;
            mouse_y_rel = sdlEvent.motion.yrel;
        }

        return Event{
            .eventType = eventType,
            .key = key,
            .mouse_x = mouse_x,
            .mouse_y = mouse_y,
            .mouse_x_rel = mouse_x_rel,
            .mouse_y_rel = mouse_y_rel,
        };
    }
};
